2023-02-08 23:05:19.987 - INFO - 33096 - azureml.train.automl._local_managed_utils.is_docker_installed:354 - Docker is installed with Docker version 20.10.22+azure-1, build 3a2c30b63ab20acfcc3f3550ea756a0561655a77
.
2023-02-08 23:12:31.935 - INFO - 33096 - azureml.train.automl._local_managed_utils.is_docker_installed:354 - Docker is installed with Docker version 20.10.22+azure-1, build 3a2c30b63ab20acfcc3f3550ea756a0561655a77
.
2023-02-08 23:12:31.938 - INFO - 33096 - azureml.train.automl.automlconfig._start_execution:229 - Submitting remote.
2023-02-08 23:14:21.403 - INFO - 33096 - azureml.train.automl._local_managed_utils.is_docker_installed:354 - Docker is installed with Docker version 20.10.22+azure-1, build 3a2c30b63ab20acfcc3f3550ea756a0561655a77
.
2023-02-08 23:14:21.411 - INFO - 33096 - azureml.train.automl.automlconfig._start_execution:229 - Submitting remote.
2023-02-08 23:28:37.078 - INFO - 33096 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-08 23:28:37.110 - INFO - 33096 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-08 23:28:37.184 - INFO - 33096 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2023-02-08 23:28:37.354 - INFO - 33096 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=169.76[ms]
2023-02-08 23:28:37.453 - INFO - 33096 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=343.26[ms]
2023-02-08 23:28:37.476 - INFO - 33096 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2023-02-08 23:28:38.043 - CRITICAL - 33096 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ImportError
Message: cannot import name 'sparse_lsqr' from 'sklearn.utils.fixes' (/anaconda/envs/jupyter_env/lib/python3.8/site-packages/sklearn/utils/fixes.py)
Traceback:
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 50, in <module>
    from azureml.automl.runtime._engineered_feature_names import (
  File "_engineered_feature_names.py", line 5, in <module>
    from azureml.training.tabular.featurization._engineered_feature_names import (
  File "_engineered_feature_names.py", line 10, in <module>
    from sklearn.cluster import MiniBatchKMeans
  File "__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "_spectral.py", line 16, in <module>
    from ..neighbors import kneighbors_graph, NearestNeighbors
  File "__init__.py", line 17, in <module>
    from ._nca import NeighborhoodComponentsAnalysis
  File "_nca.py", line 22, in <module>
    from ..decomposition import PCA
  File "__init__.py", line 17, in <module>
    from .dict_learning import dict_learning
  File "dict_learning.py", line 4, in <module>
    from . import _dict_learning
  File "_dict_learning.py", line 21, in <module>
    from ..linear_model import Lasso, orthogonal_mp_gram, LassoLars, Lars
  File "__init__.py", line 9, in <module>
    from ._base import LinearRegression
  File "_base.py", line 34, in <module>
    from ..utils.fixes import sparse_lsqr

ExceptionTarget: Unspecified
2023-02-08 23:28:38.249 - CRITICAL - 33096 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ImportError
Message: cannot import name 'sparse_lsqr' from 'sklearn.utils.fixes' (/anaconda/envs/jupyter_env/lib/python3.8/site-packages/sklearn/utils/fixes.py)
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 50, in <module>
    from azureml.automl.runtime._engineered_feature_names import (
  File "_engineered_feature_names.py", line 5, in <module>
    from azureml.training.tabular.featurization._engineered_feature_names import (
  File "_engineered_feature_names.py", line 10, in <module>
    from sklearn.cluster import MiniBatchKMeans
  File "__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "_spectral.py", line 16, in <module>
    from ..neighbors import kneighbors_graph, NearestNeighbors
  File "__init__.py", line 17, in <module>
    from ._nca import NeighborhoodComponentsAnalysis
  File "_nca.py", line 22, in <module>
    from ..decomposition import PCA
  File "__init__.py", line 17, in <module>
    from .dict_learning import dict_learning
  File "dict_learning.py", line 4, in <module>
    from . import _dict_learning
  File "_dict_learning.py", line 21, in <module>
    from ..linear_model import Lasso, orthogonal_mp_gram, LassoLars, Lars
  File "__init__.py", line 9, in <module>
    from ._base import LinearRegression
  File "_base.py", line 34, in <module>
    from ..utils.fixes import sparse_lsqr

ExceptionTarget: Unspecified
2023-02-08 23:28:38.255 - INFO - 33096 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=778.74[ms]
2023-02-08 23:28:38.258 - CRITICAL - 33096 - azureml.train.automl.run.log_traceback:227 - Type: Unclassified
Class: ImportError
Message: cannot import name 'sparse_lsqr' from 'sklearn.utils.fixes' (/anaconda/envs/jupyter_env/lib/python3.8/site-packages/sklearn/utils/fixes.py)
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 718, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 50, in <module>
    from azureml.automl.runtime._engineered_feature_names import (
  File "_engineered_feature_names.py", line 5, in <module>
    from azureml.training.tabular.featurization._engineered_feature_names import (
  File "_engineered_feature_names.py", line 10, in <module>
    from sklearn.cluster import MiniBatchKMeans
  File "__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "_spectral.py", line 16, in <module>
    from ..neighbors import kneighbors_graph, NearestNeighbors
  File "__init__.py", line 17, in <module>
    from ._nca import NeighborhoodComponentsAnalysis
  File "_nca.py", line 22, in <module>
    from ..decomposition import PCA
  File "__init__.py", line 17, in <module>
    from .dict_learning import dict_learning
  File "dict_learning.py", line 4, in <module>
    from . import _dict_learning
  File "_dict_learning.py", line 21, in <module>
    from ..linear_model import Lasso, orthogonal_mp_gram, LassoLars, Lars
  File "__init__.py", line 9, in <module>
    from ._base import LinearRegression
  File "_base.py", line 34, in <module>
    from ..utils.fixes import sparse_lsqr

ExceptionTarget: Unspecified
2023-02-08 23:28:38.258 - INFO - 33096 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1179.73[ms]
2023-02-08 23:36:16.429 - INFO - 33096 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-08 23:36:16.455 - INFO - 33096 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-08 23:36:16.480 - INFO - 33096 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2023-02-08 23:36:16.626 - INFO - 33096 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=146.04[ms]
2023-02-08 23:36:16.692 - INFO - 33096 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=237.51[ms]
2023-02-08 23:36:16.693 - INFO - 33096 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2023-02-08 23:36:17.428 - CRITICAL - 33096 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ImportError
Message: cannot import name 'sparse_lsqr' from 'sklearn.utils.fixes' (/anaconda/envs/jupyter_env/lib/python3.8/site-packages/sklearn/utils/fixes.py)
Traceback:
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 50, in <module>
    from azureml.automl.runtime._engineered_feature_names import (
  File "_engineered_feature_names.py", line 5, in <module>
    from azureml.training.tabular.featurization._engineered_feature_names import (
  File "_engineered_feature_names.py", line 10, in <module>
    from sklearn.cluster import MiniBatchKMeans
  File "__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "_spectral.py", line 16, in <module>
    from ..neighbors import kneighbors_graph, NearestNeighbors
  File "__init__.py", line 17, in <module>
    from ._nca import NeighborhoodComponentsAnalysis
  File "_nca.py", line 20, in <module>
    from ..decomposition import PCA
  File "__init__.py", line 12, in <module>
    from ._sparse_pca import SparsePCA, MiniBatchSparsePCA
  File "_sparse_pca.py", line 9, in <module>
    from ..linear_model import ridge_regression
  File "__init__.py", line 9, in <module>
    from ._base import LinearRegression
  File "_base.py", line 37, in <module>
    from ..utils.fixes import sparse_lsqr

ExceptionTarget: Unspecified
2023-02-08 23:36:17.645 - CRITICAL - 33096 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ImportError
Message: cannot import name 'sparse_lsqr' from 'sklearn.utils.fixes' (/anaconda/envs/jupyter_env/lib/python3.8/site-packages/sklearn/utils/fixes.py)
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 50, in <module>
    from azureml.automl.runtime._engineered_feature_names import (
  File "_engineered_feature_names.py", line 5, in <module>
    from azureml.training.tabular.featurization._engineered_feature_names import (
  File "_engineered_feature_names.py", line 10, in <module>
    from sklearn.cluster import MiniBatchKMeans
  File "__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "_spectral.py", line 16, in <module>
    from ..neighbors import kneighbors_graph, NearestNeighbors
  File "__init__.py", line 17, in <module>
    from ._nca import NeighborhoodComponentsAnalysis
  File "_nca.py", line 20, in <module>
    from ..decomposition import PCA
  File "__init__.py", line 12, in <module>
    from ._sparse_pca import SparsePCA, MiniBatchSparsePCA
  File "_sparse_pca.py", line 9, in <module>
    from ..linear_model import ridge_regression
  File "__init__.py", line 9, in <module>
    from ._base import LinearRegression
  File "_base.py", line 37, in <module>
    from ..utils.fixes import sparse_lsqr

ExceptionTarget: Unspecified
2023-02-08 23:36:17.646 - INFO - 33096 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=952.86[ms]
2023-02-08 23:36:17.648 - CRITICAL - 33096 - azureml.train.automl.run.log_traceback:227 - Type: Unclassified
Class: ImportError
Message: cannot import name 'sparse_lsqr' from 'sklearn.utils.fixes' (/anaconda/envs/jupyter_env/lib/python3.8/site-packages/sklearn/utils/fixes.py)
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 718, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 50, in <module>
    from azureml.automl.runtime._engineered_feature_names import (
  File "_engineered_feature_names.py", line 5, in <module>
    from azureml.training.tabular.featurization._engineered_feature_names import (
  File "_engineered_feature_names.py", line 10, in <module>
    from sklearn.cluster import MiniBatchKMeans
  File "__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "_spectral.py", line 16, in <module>
    from ..neighbors import kneighbors_graph, NearestNeighbors
  File "__init__.py", line 17, in <module>
    from ._nca import NeighborhoodComponentsAnalysis
  File "_nca.py", line 20, in <module>
    from ..decomposition import PCA
  File "__init__.py", line 12, in <module>
    from ._sparse_pca import SparsePCA, MiniBatchSparsePCA
  File "_sparse_pca.py", line 9, in <module>
    from ..linear_model import ridge_regression
  File "__init__.py", line 9, in <module>
    from ._base import LinearRegression
  File "_base.py", line 37, in <module>
    from ..utils.fixes import sparse_lsqr

ExceptionTarget: Unspecified
2023-02-08 23:36:17.648 - INFO - 33096 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1219.34[ms]
2023-02-08 23:39:09.084 - INFO - 33096 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-08 23:39:09.110 - INFO - 33096 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-08 23:39:09.132 - INFO - 33096 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2023-02-08 23:39:09.292 - INFO - 33096 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=159.48[ms]
2023-02-08 23:39:09.369 - INFO - 33096 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=259.0[ms]
2023-02-08 23:39:09.370 - INFO - 33096 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2023-02-08 23:39:09.977 - CRITICAL - 33096 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ImportError
Message: cannot import name 'sparse_lsqr' from 'sklearn.utils.fixes' (/anaconda/envs/jupyter_env/lib/python3.8/site-packages/sklearn/utils/fixes.py)
Traceback:
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 50, in <module>
    from azureml.automl.runtime._engineered_feature_names import (
  File "_engineered_feature_names.py", line 5, in <module>
    from azureml.training.tabular.featurization._engineered_feature_names import (
  File "_engineered_feature_names.py", line 10, in <module>
    from sklearn.cluster import MiniBatchKMeans
  File "__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "_spectral.py", line 16, in <module>
    from ..neighbors import kneighbors_graph, NearestNeighbors
  File "__init__.py", line 17, in <module>
    from ._nca import NeighborhoodComponentsAnalysis
  File "_nca.py", line 20, in <module>
    from ..decomposition import PCA
  File "__init__.py", line 12, in <module>
    from ._sparse_pca import SparsePCA, MiniBatchSparsePCA
  File "_sparse_pca.py", line 9, in <module>
    from ..linear_model import ridge_regression
  File "__init__.py", line 9, in <module>
    from ._base import LinearRegression
  File "_base.py", line 37, in <module>
    from ..utils.fixes import sparse_lsqr

ExceptionTarget: Unspecified
2023-02-08 23:39:10.249 - CRITICAL - 33096 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ImportError
Message: cannot import name 'sparse_lsqr' from 'sklearn.utils.fixes' (/anaconda/envs/jupyter_env/lib/python3.8/site-packages/sklearn/utils/fixes.py)
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 50, in <module>
    from azureml.automl.runtime._engineered_feature_names import (
  File "_engineered_feature_names.py", line 5, in <module>
    from azureml.training.tabular.featurization._engineered_feature_names import (
  File "_engineered_feature_names.py", line 10, in <module>
    from sklearn.cluster import MiniBatchKMeans
  File "__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "_spectral.py", line 16, in <module>
    from ..neighbors import kneighbors_graph, NearestNeighbors
  File "__init__.py", line 17, in <module>
    from ._nca import NeighborhoodComponentsAnalysis
  File "_nca.py", line 20, in <module>
    from ..decomposition import PCA
  File "__init__.py", line 12, in <module>
    from ._sparse_pca import SparsePCA, MiniBatchSparsePCA
  File "_sparse_pca.py", line 9, in <module>
    from ..linear_model import ridge_regression
  File "__init__.py", line 9, in <module>
    from ._base import LinearRegression
  File "_base.py", line 37, in <module>
    from ..utils.fixes import sparse_lsqr

ExceptionTarget: Unspecified
2023-02-08 23:39:10.249 - INFO - 33096 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=879.46[ms]
2023-02-08 23:39:10.251 - CRITICAL - 33096 - azureml.train.automl.run.log_traceback:227 - Type: Unclassified
Class: ImportError
Message: cannot import name 'sparse_lsqr' from 'sklearn.utils.fixes' (/anaconda/envs/jupyter_env/lib/python3.8/site-packages/sklearn/utils/fixes.py)
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 718, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 50, in <module>
    from azureml.automl.runtime._engineered_feature_names import (
  File "_engineered_feature_names.py", line 5, in <module>
    from azureml.training.tabular.featurization._engineered_feature_names import (
  File "_engineered_feature_names.py", line 10, in <module>
    from sklearn.cluster import MiniBatchKMeans
  File "__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "_spectral.py", line 16, in <module>
    from ..neighbors import kneighbors_graph, NearestNeighbors
  File "__init__.py", line 17, in <module>
    from ._nca import NeighborhoodComponentsAnalysis
  File "_nca.py", line 20, in <module>
    from ..decomposition import PCA
  File "__init__.py", line 12, in <module>
    from ._sparse_pca import SparsePCA, MiniBatchSparsePCA
  File "_sparse_pca.py", line 9, in <module>
    from ..linear_model import ridge_regression
  File "__init__.py", line 9, in <module>
    from ._base import LinearRegression
  File "_base.py", line 37, in <module>
    from ..utils.fixes import sparse_lsqr

ExceptionTarget: Unspecified
2023-02-08 23:39:10.251 - INFO - 33096 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1167.75[ms]
2023-02-08 23:40:08.265 - INFO - 33096 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-08 23:40:08.291 - INFO - 33096 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-08 23:40:08.314 - INFO - 33096 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2023-02-08 23:40:08.482 - INFO - 33096 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=168.32[ms]
2023-02-08 23:40:08.561 - INFO - 33096 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=269.73[ms]
2023-02-08 23:40:08.561 - INFO - 33096 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2023-02-08 23:40:09.212 - CRITICAL - 33096 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ImportError
Message: cannot import name 'sparse_lsqr' from 'sklearn.utils.fixes' (/anaconda/envs/jupyter_env/lib/python3.8/site-packages/sklearn/utils/fixes.py)
Traceback:
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 50, in <module>
    from azureml.automl.runtime._engineered_feature_names import (
  File "_engineered_feature_names.py", line 5, in <module>
    from azureml.training.tabular.featurization._engineered_feature_names import (
  File "_engineered_feature_names.py", line 10, in <module>
    from sklearn.cluster import MiniBatchKMeans
  File "__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "_spectral.py", line 16, in <module>
    from ..neighbors import kneighbors_graph, NearestNeighbors
  File "__init__.py", line 17, in <module>
    from ._nca import NeighborhoodComponentsAnalysis
  File "_nca.py", line 20, in <module>
    from ..decomposition import PCA
  File "__init__.py", line 12, in <module>
    from ._sparse_pca import SparsePCA, MiniBatchSparsePCA
  File "_sparse_pca.py", line 9, in <module>
    from ..linear_model import ridge_regression
  File "__init__.py", line 9, in <module>
    from ._base import LinearRegression
  File "_base.py", line 37, in <module>
    from ..utils.fixes import sparse_lsqr

ExceptionTarget: Unspecified
2023-02-08 23:40:09.460 - CRITICAL - 33096 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ImportError
Message: cannot import name 'sparse_lsqr' from 'sklearn.utils.fixes' (/anaconda/envs/jupyter_env/lib/python3.8/site-packages/sklearn/utils/fixes.py)
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 50, in <module>
    from azureml.automl.runtime._engineered_feature_names import (
  File "_engineered_feature_names.py", line 5, in <module>
    from azureml.training.tabular.featurization._engineered_feature_names import (
  File "_engineered_feature_names.py", line 10, in <module>
    from sklearn.cluster import MiniBatchKMeans
  File "__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "_spectral.py", line 16, in <module>
    from ..neighbors import kneighbors_graph, NearestNeighbors
  File "__init__.py", line 17, in <module>
    from ._nca import NeighborhoodComponentsAnalysis
  File "_nca.py", line 20, in <module>
    from ..decomposition import PCA
  File "__init__.py", line 12, in <module>
    from ._sparse_pca import SparsePCA, MiniBatchSparsePCA
  File "_sparse_pca.py", line 9, in <module>
    from ..linear_model import ridge_regression
  File "__init__.py", line 9, in <module>
    from ._base import LinearRegression
  File "_base.py", line 37, in <module>
    from ..utils.fixes import sparse_lsqr

ExceptionTarget: Unspecified
2023-02-08 23:40:09.461 - INFO - 33096 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=899.52[ms]
2023-02-08 23:40:09.462 - CRITICAL - 33096 - azureml.train.automl.run.log_traceback:227 - Type: Unclassified
Class: ImportError
Message: cannot import name 'sparse_lsqr' from 'sklearn.utils.fixes' (/anaconda/envs/jupyter_env/lib/python3.8/site-packages/sklearn/utils/fixes.py)
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 718, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 50, in <module>
    from azureml.automl.runtime._engineered_feature_names import (
  File "_engineered_feature_names.py", line 5, in <module>
    from azureml.training.tabular.featurization._engineered_feature_names import (
  File "_engineered_feature_names.py", line 10, in <module>
    from sklearn.cluster import MiniBatchKMeans
  File "__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "_spectral.py", line 16, in <module>
    from ..neighbors import kneighbors_graph, NearestNeighbors
  File "__init__.py", line 17, in <module>
    from ._nca import NeighborhoodComponentsAnalysis
  File "_nca.py", line 20, in <module>
    from ..decomposition import PCA
  File "__init__.py", line 12, in <module>
    from ._sparse_pca import SparsePCA, MiniBatchSparsePCA
  File "_sparse_pca.py", line 9, in <module>
    from ..linear_model import ridge_regression
  File "__init__.py", line 9, in <module>
    from ._base import LinearRegression
  File "_base.py", line 37, in <module>
    from ..utils.fixes import sparse_lsqr

ExceptionTarget: Unspecified
2023-02-08 23:40:09.463 - INFO - 33096 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1198.09[ms]
2023-02-08 23:41:32.526 - INFO - 33096 - azureml.train.automl._local_managed_utils.is_docker_installed:354 - Docker is installed with Docker version 20.10.22+azure-1, build 3a2c30b63ab20acfcc3f3550ea756a0561655a77
.
2023-02-08 23:42:59.654 - INFO - 62929 - azureml.train.automl._local_managed_utils.is_docker_installed:354 - Docker is installed with Docker version 20.10.22+azure-1, build 3a2c30b63ab20acfcc3f3550ea756a0561655a77
.
2023-02-08 23:42:59.662 - INFO - 62929 - azureml.train.automl.automlconfig._start_execution:229 - Submitting remote.
2023-02-08 23:53:25.253 - INFO - 62929 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-08 23:53:25.296 - INFO - 62929 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-08 23:53:25.334 - INFO - 62929 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2023-02-08 23:53:25.707 - INFO - 62929 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=372.76[ms]
2023-02-08 23:53:25.820 - INFO - 62929 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=523.69[ms]
2023-02-08 23:53:25.835 - INFO - 62929 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2023-02-08 23:53:27.374 - WARNING - 62929 - azureml.training.tabular.models._timeseries._prophet_model.<module>:32 - Unable to import fbprophet.
2023-02-08 23:53:27.928 - INFO - 62929 - azureml.automl.runtime.featurization.data_transformer.__init__:190 - Feature sweeping enabled: False
2023-02-08 23:53:27.934 - INFO - 62929 - azureml.automl.runtime.featurization.data_transformer.__init__:191 - Feature sweeping timeout: 86400
2023-02-08 23:53:28.802 - CRITICAL - 62929 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ModuleNotFoundError
Message: No module named 'xgboost'
Traceback:
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]

ExceptionTarget: Unspecified
2023-02-08 23:53:28.831 - CRITICAL - 62929 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: IncompatibleOrMissingDependency
Class: ConfigException
Message: ConfigException:
	Message: The model you attempted to retrieve requires 'xgboost' to be installed at '==1.3.3'. Please install 'xgboost==1.3.3' (e.g. `pip install xgboost==1.3.3`) and then rerun the previous command.
	InnerException: ModuleNotFoundError: No module named 'xgboost'
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "The model you attempted to retrieve requires 'xgboost' to be installed at '==1.3.3'. Please install 'xgboost==1.3.3' (e.g. `pip install xgboost==1.3.3`) and then rerun the previous command.",
        "target": "get_output",
        "inner_error": {
            "code": "NotSupported",
            "inner_error": {
                "code": "IncompatibleOrMissingDependency"
            }
        },
        "reference_code": "c520b52d-f8ca-4236-ab93-118b9ae3173c"
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 190, in _load_automl_model
    raise ConfigException._with_error(

ExceptionTarget: get_output
2023-02-08 23:53:28.836 - INFO - 62929 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=3001.48[ms]
2023-02-08 23:53:28.842 - CRITICAL - 62929 - azureml.train.automl.run.log_traceback:227 - Type: IncompatibleOrMissingDependency
Class: ConfigException
Message: ConfigException:
	Message: The model you attempted to retrieve requires 'xgboost' to be installed at '==1.3.3'. Please install 'xgboost==1.3.3' (e.g. `pip install xgboost==1.3.3`) and then rerun the previous command.
	InnerException: ModuleNotFoundError: No module named 'xgboost'
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "The model you attempted to retrieve requires 'xgboost' to be installed at '==1.3.3'. Please install 'xgboost==1.3.3' (e.g. `pip install xgboost==1.3.3`) and then rerun the previous command.",
        "target": "get_output",
        "inner_error": {
            "code": "NotSupported",
            "inner_error": {
                "code": "IncompatibleOrMissingDependency"
            }
        },
        "reference_code": "c520b52d-f8ca-4236-ab93-118b9ae3173c"
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 718, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 190, in _load_automl_model
    raise ConfigException._with_error(

ExceptionTarget: get_output
2023-02-08 23:53:28.846 - INFO - 62929 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=3593.02[ms]
2023-02-08 23:53:59.613 - INFO - 62929 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-08 23:53:59.640 - INFO - 62929 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-08 23:53:59.662 - INFO - 62929 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2023-02-08 23:53:59.805 - INFO - 62929 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=142.98[ms]
2023-02-08 23:53:59.894 - INFO - 62929 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=253.99[ms]
2023-02-08 23:53:59.894 - INFO - 62929 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2023-02-08 23:54:00.317 - INFO - 62929 - azureml.automl.runtime.featurization.data_transformer.__init__:190 - Feature sweeping enabled: False
2023-02-08 23:54:00.318 - INFO - 62929 - azureml.automl.runtime.featurization.data_transformer.__init__:191 - Feature sweeping timeout: 86400
2023-02-08 23:54:00.324 - CRITICAL - 62929 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ModuleNotFoundError
Message: No module named 'xgboost'
Traceback:
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]

ExceptionTarget: Unspecified
2023-02-08 23:54:00.341 - CRITICAL - 62929 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: IncompatibleOrMissingDependency
Class: ConfigException
Message: ConfigException:
	Message: The model you attempted to retrieve requires 'xgboost' to be installed at '==1.3.3'. Please install 'xgboost==1.3.3' (e.g. `pip install xgboost==1.3.3`) and then rerun the previous command.
	InnerException: ModuleNotFoundError: No module named 'xgboost'
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "The model you attempted to retrieve requires 'xgboost' to be installed at '==1.3.3'. Please install 'xgboost==1.3.3' (e.g. `pip install xgboost==1.3.3`) and then rerun the previous command.",
        "target": "get_output",
        "inner_error": {
            "code": "NotSupported",
            "inner_error": {
                "code": "IncompatibleOrMissingDependency"
            }
        },
        "reference_code": "c520b52d-f8ca-4236-ab93-118b9ae3173c"
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 190, in _load_automl_model
    raise ConfigException._with_error(

ExceptionTarget: get_output
2023-02-08 23:54:00.341 - INFO - 62929 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=447.28[ms]
2023-02-08 23:54:00.342 - CRITICAL - 62929 - azureml.train.automl.run.log_traceback:227 - Type: IncompatibleOrMissingDependency
Class: ConfigException
Message: ConfigException:
	Message: The model you attempted to retrieve requires 'xgboost' to be installed at '==1.3.3'. Please install 'xgboost==1.3.3' (e.g. `pip install xgboost==1.3.3`) and then rerun the previous command.
	InnerException: ModuleNotFoundError: No module named 'xgboost'
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "The model you attempted to retrieve requires 'xgboost' to be installed at '==1.3.3'. Please install 'xgboost==1.3.3' (e.g. `pip install xgboost==1.3.3`) and then rerun the previous command.",
        "target": "get_output",
        "inner_error": {
            "code": "NotSupported",
            "inner_error": {
                "code": "IncompatibleOrMissingDependency"
            }
        },
        "reference_code": "c520b52d-f8ca-4236-ab93-118b9ae3173c"
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 718, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 190, in _load_automl_model
    raise ConfigException._with_error(

ExceptionTarget: get_output
2023-02-08 23:54:00.342 - INFO - 62929 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=728.99[ms]
2023-02-08 23:55:27.545 - INFO - 62929 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-08 23:55:27.576 - INFO - 62929 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-08 23:55:27.605 - INFO - 62929 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2023-02-08 23:55:27.760 - INFO - 62929 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=155.36[ms]
2023-02-08 23:55:27.835 - INFO - 62929 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=258.66[ms]
2023-02-08 23:55:27.836 - INFO - 62929 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2023-02-08 23:55:28.372 - INFO - 62929 - azureml.automl.runtime.featurization.data_transformer.__init__:190 - Feature sweeping enabled: False
2023-02-08 23:55:28.373 - INFO - 62929 - azureml.automl.runtime.featurization.data_transformer.__init__:191 - Feature sweeping timeout: 86400
2023-02-08 23:55:28.866 - CRITICAL - 62929 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ModuleNotFoundError
Message: No module named 'sklearn.neighbors._dist_metrics'
Traceback:
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]

ExceptionTarget: Unspecified
2023-02-08 23:55:29.092 - CRITICAL - 62929 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ModuleNotFoundError
Message: No module named 'sklearn.neighbors._dist_metrics'
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]

ExceptionTarget: Unspecified
2023-02-08 23:55:29.092 - INFO - 62929 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=1256.65[ms]
2023-02-08 23:55:29.093 - CRITICAL - 62929 - azureml.train.automl.run.log_traceback:227 - Type: Unclassified
Class: ModuleNotFoundError
Message: No module named 'sklearn.neighbors._dist_metrics'
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 718, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]

ExceptionTarget: Unspecified
2023-02-08 23:55:29.093 - INFO - 62929 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1547.87[ms]
2023-02-08 23:59:03.659 - INFO - 62929 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-08 23:59:03.680 - INFO - 62929 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-08 23:59:03.749 - INFO - 62929 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2023-02-08 23:59:04.418 - INFO - 62929 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=668.74[ms]
2023-02-08 23:59:04.857 - INFO - 62929 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=1176.84[ms]
2023-02-08 23:59:04.858 - INFO - 62929 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2023-02-08 23:59:07.220 - INFO - 62929 - azureml.automl.runtime.featurization.data_transformer.__init__:190 - Feature sweeping enabled: False
2023-02-08 23:59:07.233 - INFO - 62929 - azureml.automl.runtime.featurization.data_transformer.__init__:191 - Feature sweeping timeout: 86400
2023-02-08 23:59:07.282 - CRITICAL - 62929 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: TypeError
Message: Cannot convert sklearn.neighbors._dist_metrics.ManhattanDistance to sklearn.metrics._dist_metrics.DistanceMetric
Traceback:
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "_binary_tree.pxi", line 1064, in sklearn.neighbors._kd_tree.BinaryTree.__setstate__

ExceptionTarget: Unspecified
2023-02-08 23:59:08.107 - CRITICAL - 62929 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: TypeError
Message: Cannot convert sklearn.neighbors._dist_metrics.ManhattanDistance to sklearn.metrics._dist_metrics.DistanceMetric
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "_binary_tree.pxi", line 1064, in sklearn.neighbors._kd_tree.BinaryTree.__setstate__

ExceptionTarget: Unspecified
2023-02-08 23:59:08.108 - INFO - 62929 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=3250.02[ms]
2023-02-08 23:59:08.108 - CRITICAL - 62929 - azureml.train.automl.run.log_traceback:227 - Type: Unclassified
Class: TypeError
Message: Cannot convert sklearn.neighbors._dist_metrics.ManhattanDistance to sklearn.metrics._dist_metrics.DistanceMetric
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 718, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "_binary_tree.pxi", line 1064, in sklearn.neighbors._kd_tree.BinaryTree.__setstate__

ExceptionTarget: Unspecified
2023-02-08 23:59:08.108 - INFO - 62929 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=4449.06[ms]
2023-02-09 00:24:12.481 - INFO - 62929 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-09 00:24:12.508 - INFO - 62929 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-09 00:24:12.533 - INFO - 62929 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2023-02-09 00:24:12.734 - INFO - 62929 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=200.88[ms]
2023-02-09 00:24:12.839 - INFO - 62929 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=330.12[ms]
2023-02-09 00:24:12.839 - INFO - 62929 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2023-02-09 00:24:14.128 - INFO - 62929 - azureml.automl.runtime.featurization.data_transformer.__init__:190 - Feature sweeping enabled: False
2023-02-09 00:24:14.128 - INFO - 62929 - azureml.automl.runtime.featurization.data_transformer.__init__:191 - Feature sweeping timeout: 86400
2023-02-09 00:24:14.182 - CRITICAL - 62929 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: TypeError
Message: Cannot convert sklearn.neighbors._dist_metrics.ManhattanDistance to sklearn.metrics._dist_metrics.DistanceMetric
Traceback:
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "_binary_tree.pxi", line 1064, in sklearn.neighbors._kd_tree.BinaryTree.__setstate__

ExceptionTarget: Unspecified
2023-02-09 00:24:14.431 - CRITICAL - 62929 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: TypeError
Message: Cannot convert sklearn.neighbors._dist_metrics.ManhattanDistance to sklearn.metrics._dist_metrics.DistanceMetric
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "_binary_tree.pxi", line 1064, in sklearn.neighbors._kd_tree.BinaryTree.__setstate__

ExceptionTarget: Unspecified
2023-02-09 00:24:14.431 - INFO - 62929 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=1592.23[ms]
2023-02-09 00:24:14.432 - CRITICAL - 62929 - azureml.train.automl.run.log_traceback:227 - Type: Unclassified
Class: TypeError
Message: Cannot convert sklearn.neighbors._dist_metrics.ManhattanDistance to sklearn.metrics._dist_metrics.DistanceMetric
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 718, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "_binary_tree.pxi", line 1064, in sklearn.neighbors._kd_tree.BinaryTree.__setstate__

ExceptionTarget: Unspecified
2023-02-09 00:24:14.432 - INFO - 62929 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1950.91[ms]
2023-02-09 00:30:43.740 - INFO - 62929 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-09 00:30:43.767 - INFO - 62929 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-09 00:30:43.790 - INFO - 62929 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2023-02-09 00:30:43.962 - INFO - 62929 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=172.02[ms]
2023-02-09 00:30:44.025 - INFO - 62929 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=257.38[ms]
2023-02-09 00:30:44.025 - INFO - 62929 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2023-02-09 00:30:44.680 - INFO - 62929 - azureml.automl.runtime.featurization.data_transformer.__init__:190 - Feature sweeping enabled: False
2023-02-09 00:30:44.680 - INFO - 62929 - azureml.automl.runtime.featurization.data_transformer.__init__:191 - Feature sweeping timeout: 86400
2023-02-09 00:30:44.719 - CRITICAL - 62929 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: TypeError
Message: Cannot convert sklearn.neighbors._dist_metrics.ManhattanDistance to sklearn.metrics._dist_metrics.DistanceMetric
Traceback:
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "_binary_tree.pxi", line 1064, in sklearn.neighbors._kd_tree.BinaryTree.__setstate__

ExceptionTarget: Unspecified
2023-02-09 00:30:44.886 - CRITICAL - 62929 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: TypeError
Message: Cannot convert sklearn.neighbors._dist_metrics.ManhattanDistance to sklearn.metrics._dist_metrics.DistanceMetric
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "_binary_tree.pxi", line 1064, in sklearn.neighbors._kd_tree.BinaryTree.__setstate__

ExceptionTarget: Unspecified
2023-02-09 00:30:44.886 - INFO - 62929 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=860.74[ms]
2023-02-09 00:30:44.887 - CRITICAL - 62929 - azureml.train.automl.run.log_traceback:227 - Type: Unclassified
Class: TypeError
Message: Cannot convert sklearn.neighbors._dist_metrics.ManhattanDistance to sklearn.metrics._dist_metrics.DistanceMetric
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 718, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "_binary_tree.pxi", line 1064, in sklearn.neighbors._kd_tree.BinaryTree.__setstate__

ExceptionTarget: Unspecified
2023-02-09 00:30:44.887 - INFO - 62929 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1146.87[ms]
2023-02-09 00:32:25.335 - INFO - 92354 - azureml.train.automl._local_managed_utils.is_docker_installed:354 - Docker is installed with Docker version 20.10.22+azure-1, build 3a2c30b63ab20acfcc3f3550ea756a0561655a77
.
2023-02-09 00:32:25.344 - INFO - 92354 - azureml.train.automl.automlconfig._start_execution:229 - Submitting remote.
2023-02-09 00:47:13.570 - INFO - 92354 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-09 00:47:13.598 - INFO - 92354 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-09 00:47:13.658 - INFO - 92354 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2023-02-09 00:47:13.868 - INFO - 92354 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=209.41[ms]
2023-02-09 00:47:13.954 - INFO - 92354 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=355.65[ms]
2023-02-09 00:47:13.962 - INFO - 92354 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2023-02-09 00:47:16.286 - CRITICAL - 92354 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: PermissionError
Message: [Errno 1] Operation not permitted: '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nimbusml/internal/libs/pybridge.so'
Traceback:
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 56, in <module>
    from azureml.automl.runtime.featurizer.transformer.categorical import LabelEncoderTransformer
  File "__init__.py", line 7, in <module>
    from .categorical import CategoricalFeaturizers, CatImputer, LabelEncoderTransformer, \
  File "__init__.py", line 7, in <module>
    from .labelencoder_transformer import LabelEncoderTransformer
  File "labelencoder_transformer.py", line 5, in <module>
    from azureml.training.tabular.featurization.categorical.labelencoder_transformer import LabelEncoderTransformer
  File "labelencoder_transformer.py", line 12, in <module>
    from ...models._abstract_model_wrapper import _AbstractModelWrapper
  File "__init__.py", line 6, in <module>
    from .forecasting_pipeline_wrapper import RegressionPipeline, ForecastingPipelineWrapper
  File "forecasting_pipeline_wrapper.py", line 10, in <module>
    import nimbusml
  File "__init__.py", line 33, in <module>
    os.chmod(dotso, 0o755)

ExceptionTarget: Unspecified
2023-02-09 00:47:16.500 - CRITICAL - 92354 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: PermissionError
Message: [Errno 1] Operation not permitted: '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nimbusml/internal/libs/pybridge.so'
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 56, in <module>
    from azureml.automl.runtime.featurizer.transformer.categorical import LabelEncoderTransformer
  File "__init__.py", line 7, in <module>
    from .categorical import CategoricalFeaturizers, CatImputer, LabelEncoderTransformer, \
  File "__init__.py", line 7, in <module>
    from .labelencoder_transformer import LabelEncoderTransformer
  File "labelencoder_transformer.py", line 5, in <module>
    from azureml.training.tabular.featurization.categorical.labelencoder_transformer import LabelEncoderTransformer
  File "labelencoder_transformer.py", line 12, in <module>
    from ...models._abstract_model_wrapper import _AbstractModelWrapper
  File "__init__.py", line 6, in <module>
    from .forecasting_pipeline_wrapper import RegressionPipeline, ForecastingPipelineWrapper
  File "forecasting_pipeline_wrapper.py", line 10, in <module>
    import nimbusml
  File "__init__.py", line 33, in <module>
    os.chmod(dotso, 0o755)

ExceptionTarget: Unspecified
2023-02-09 00:47:16.501 - INFO - 92354 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=2539.27[ms]
2023-02-09 00:47:16.516 - CRITICAL - 92354 - azureml.train.automl.run.log_traceback:227 - Type: Unclassified
Class: PermissionError
Message: [Errno 1] Operation not permitted: '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nimbusml/internal/libs/pybridge.so'
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 718, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 56, in <module>
    from azureml.automl.runtime.featurizer.transformer.categorical import LabelEncoderTransformer
  File "__init__.py", line 7, in <module>
    from .categorical import CategoricalFeaturizers, CatImputer, LabelEncoderTransformer, \
  File "__init__.py", line 7, in <module>
    from .labelencoder_transformer import LabelEncoderTransformer
  File "labelencoder_transformer.py", line 5, in <module>
    from azureml.training.tabular.featurization.categorical.labelencoder_transformer import LabelEncoderTransformer
  File "labelencoder_transformer.py", line 12, in <module>
    from ...models._abstract_model_wrapper import _AbstractModelWrapper
  File "__init__.py", line 6, in <module>
    from .forecasting_pipeline_wrapper import RegressionPipeline, ForecastingPipelineWrapper
  File "forecasting_pipeline_wrapper.py", line 10, in <module>
    import nimbusml
  File "__init__.py", line 33, in <module>
    os.chmod(dotso, 0o755)

ExceptionTarget: Unspecified
2023-02-09 00:47:16.517 - INFO - 92354 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=2946.68[ms]
2023-02-09 00:53:09.451 - INFO - 92354 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-09 00:53:09.470 - INFO - 92354 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-09 00:53:09.505 - INFO - 92354 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2023-02-09 00:53:09.689 - INFO - 92354 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=184.07[ms]
2023-02-09 00:53:09.771 - INFO - 92354 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=301.29[ms]
2023-02-09 00:53:09.772 - INFO - 92354 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2023-02-09 00:53:10.403 - CRITICAL - 92354 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: PermissionError
Message: [Errno 1] Operation not permitted: '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nimbusml/internal/libs/pybridge.so'
Traceback:
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 56, in <module>
    from azureml.automl.runtime.featurizer.transformer.categorical import LabelEncoderTransformer
  File "__init__.py", line 7, in <module>
    from .categorical import CategoricalFeaturizers, CatImputer, LabelEncoderTransformer, \
  File "__init__.py", line 8, in <module>
    from .categorical_featurizers import CategoricalFeaturizers
  File "categorical_featurizers.py", line 8, in <module>
    from nimbusml.feature_extraction.categorical import OneHotVectorizer as NimbusMLOneHotVectorizer
  File "__init__.py", line 33, in <module>
    os.chmod(dotso, 0o755)

ExceptionTarget: Unspecified
2023-02-09 00:53:10.611 - CRITICAL - 92354 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: PermissionError
Message: [Errno 1] Operation not permitted: '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nimbusml/internal/libs/pybridge.so'
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 56, in <module>
    from azureml.automl.runtime.featurizer.transformer.categorical import LabelEncoderTransformer
  File "__init__.py", line 7, in <module>
    from .categorical import CategoricalFeaturizers, CatImputer, LabelEncoderTransformer, \
  File "__init__.py", line 8, in <module>
    from .categorical_featurizers import CategoricalFeaturizers
  File "categorical_featurizers.py", line 8, in <module>
    from nimbusml.feature_extraction.categorical import OneHotVectorizer as NimbusMLOneHotVectorizer
  File "__init__.py", line 33, in <module>
    os.chmod(dotso, 0o755)

ExceptionTarget: Unspecified
2023-02-09 00:53:10.611 - INFO - 92354 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=839.98[ms]
2023-02-09 00:53:10.612 - CRITICAL - 92354 - azureml.train.automl.run.log_traceback:227 - Type: Unclassified
Class: PermissionError
Message: [Errno 1] Operation not permitted: '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nimbusml/internal/libs/pybridge.so'
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 718, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 56, in <module>
    from azureml.automl.runtime.featurizer.transformer.categorical import LabelEncoderTransformer
  File "__init__.py", line 7, in <module>
    from .categorical import CategoricalFeaturizers, CatImputer, LabelEncoderTransformer, \
  File "__init__.py", line 8, in <module>
    from .categorical_featurizers import CategoricalFeaturizers
  File "categorical_featurizers.py", line 8, in <module>
    from nimbusml.feature_extraction.categorical import OneHotVectorizer as NimbusMLOneHotVectorizer
  File "__init__.py", line 33, in <module>
    os.chmod(dotso, 0o755)

ExceptionTarget: Unspecified
2023-02-09 00:53:10.613 - INFO - 92354 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1161.11[ms]
2023-02-09 00:55:02.736 - INFO - 92354 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-09 00:55:02.763 - INFO - 92354 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-09 00:55:02.788 - INFO - 92354 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2023-02-09 00:55:02.993 - INFO - 92354 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=204.46[ms]
2023-02-09 00:55:03.103 - INFO - 92354 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=340.53[ms]
2023-02-09 00:55:03.104 - INFO - 92354 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2023-02-09 00:55:08.910 - INFO - 92354 - azureml.automl.runtime.featurization.data_transformer.__init__:190 - Feature sweeping enabled: False
2023-02-09 00:55:08.911 - INFO - 92354 - azureml.automl.runtime.featurization.data_transformer.__init__:191 - Feature sweeping timeout: 86400
2023-02-09 00:55:11.540 - INFO - 92354 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Success, Duration=8435.48[ms]
2023-02-09 00:55:11.555 - INFO - 92354 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=8818.31[ms]
2023-02-09 00:56:02.930 - INFO - 92354 - azureml.train.automl.run._log_activity:55 - ActivityStarted: RegisterModel
2023-02-09 00:56:02.958 - INFO - 92354 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2023-02-09 00:56:03.145 - INFO - 92354 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=187.28[ms]
2023-02-09 00:56:04.585 - INFO - 92354 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=RegisterModel, HowEnded=Success, Duration=1654.89[ms]
